name: null
favicon: null
layout_spectrum: 0.3474190514534712
typography_spectrum: 0.8577987302560359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.49944953387603164
  lightness: 0.033292006235569715
  saturation: 0.044965701876208186
  rhythmicContrast: 0.5637810637708753
purpose: []
