name: Living Data
favicon: null
layout_spectrum: 0.77814
typography_spectrum: 0.3819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0907'
    - '#ffffff'
    - '#c4d5d5'
    - '#8aa1a3'
    - '#6c6d67'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
